---
title: "Chapter_2"
author: "Kianté Fernandez"
date: "2/3/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
#install.packages("lobstr")
library(lobstr)
```

```{r}
x <- c(1,2,3)
y <- x
obj_addr(x)
#> [1] "0x7fe11b31b1e8"
obj_addr(y)
#> [1] "0x7fe11b31b1e8"
```

```{r}
a <- 1:10
b <- a
obj_addr(a)
obj_addr(b)

c <- b
obj_addr(c)

d <- 1:10
obj_addr(d)
```

```{r}
means <- list(
  mean,
  base::mean,
  get("mean"),
  evalq(mean),
  match.fun("mean")
)

for (i in 1:5){
  address <- obj_addr(means[[i]])
  print(address)
}
make.names()
```

```{r}
x <- c(1, 2, 3)
cat(tracemem(x), "\n")
y <- x
y[[3]] <- 4L
y[[3]] <- 5L
untracemem(x)
```

```{r}
f <- function(a) {
  a
}

x <- c(1, 2, 3)
cat(tracemem(x), "\n")
#> <0x7fe1121693a8>

z <- f(x)
# there's no copy here!
z
untracemem(x)
```

```{r}
x <- c(1L, 2L, 3L)
tracemem(x)

x[[3]] <- 4

```

```{r}
x <- list(1:10)
x[[2]] <- x
```


```{r}
y <- rep(list(runif(1e4)), 100)

object.size(y)
#> 8005648 bytes
obj_size(y)
#> 80,896 B
```

```{r}
funs <- list(mean, sd, var)
obj_size(funs)
#> 17,608 B
```


```{r}
a <- runif(1e6)
obj_size(a)

b <- list(a, a)
obj_size(b)
obj_size(a, b)

b[[1]][[1]] <- 10
obj_size(b)
obj_size(a, b)

b[[2]][[1]] <- 10
obj_size(b)
obj_size(a, b)
```

```{r}
library(bench)
sub_med1 <- function(x){
  med <- median(x)
  return(x - med)
}
sub_med2 <- function(x){
  return(x - median(x))
}
x <- runif(40)
sub_med1(x)
sub_med2(x)
results <- bench::mark(
  sub_med1(x),
  sub_med2(x)
)
summary(results)
```

